version: "3.5"
services:
  webserver:
    image: fuerzastudio/nginx-php-fpm:version-.1.0.5
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./nginx:/etc/nginx
      - ./cache:/var/run/nginx-cache
      - /var/www:/var/www
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
    networks: 
      dev:
        ipv4_address: 171.28.5.10
  server-database:
    image: mariadb:10.5.9
    container_name: serverdb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passroot
      - MYSQL_USER=example_usr              
      - MYSQL_PASSWORD=example_pass
      - MYSQL_DATABASE=example_db               
    ports:
      - "3306:3306"
    networks: 
      dev:
        ipv4_address: 171.28.5.11

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin
    hostname: phpmyadmin
    environment:
      - PMA_HOSTS=171.28.5.11
      - UPLOAD_LIMIT=20480000K
    restart: always
    ports:
      - "8081:80"
    
    links:
      - server-database
    depends_on:
      - server-database
    volumes:
      - /sessions
    networks:
      dev:
        ipv4_address: 171.28.5.12

networks: 
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 171.28.0.0/16
