version: "3.5"
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/www:/var/www
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/data/letsencrypt --email mail@mail.com --agree-tos --no-eff-email --force-renewal -d example.com  -d www.example.com