version: "3.5"
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/www:/var/www
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/lib/letsencrypt/webroot --email lopesma2@gmail.com --agree-tos --no-eff-email --force-renewal -d quadranteti.com.br  -d www.quadranteti.com.br