version: "3.5"
services:
  webserver:
    image: fuerzastudio/nginx-php-fpm:version-.1.0.5
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./nginx:/etc/nginx
      - ./cache:/var/run/nginx-cache
      - /var/www:/var/www
      - /data/letsencrypt:/data/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
    networks: 
      dev:
        ipv4_address: 171.28.5.10
  server-database:
    image: mariadb:10.5.9
    container_name: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passroot
      - MYSQL_USER=example_usr              
      - MYSQL_PASSWORD=example_pass
      - MYSQL_DATABASE=example_db               
    ports:
      - "3306:3306"
    networks: 
      dev:
        ipv4_address: 171.28.5.11

  postgres:
    image: postgres:13.3
    container_name: postgres_dev
    environment:
      POSTGRES_USER: fuerza
      POSTGRES_PASSWORD: f&HUW4xSyedR
      POSTGRES_DB: postgres 
    volumes:
      - ./databases/pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    networks:
      dev:
        ipv4_address: 171.28.5.12

  pgadmin-compose:
    image: dpage/pgadmin4 
    container_name: pgadmin4 
    environment:
      PGADMIN_DEFAULT_EMAIL: "lopesma2@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./databases/pgdadmin:/var/lib/postgresql/data
    restart: always
    ports:
      - "8081:80"
    networks:
      dev:
        ipv4_address: 171.28.5.13 

networks: 
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 171.28.0.0/16
